FROM ubuntu:xenial

RUN apt-get update

RUN apt install -y libboost-all-dev git-core tar unzip wget bzip2 build-essential \
    autoconf libtool libxml2-dev libgeos-dev libgeos++-dev libpq-dev libbz2-dev \
    libproj-dev munin-node munin libprotobuf-c0-dev protobuf-c-compiler \
    libfreetype6-dev libtiff5-dev libicu-dev libgdal-dev libcairo-dev \
    libcairomm-1.0-dev apache2 apache2-dev libagg-dev liblua5.2-dev ttf-unifont \
    lua5.1 liblua5.1-dev libgeotiff-epsg curl gdal-bin libmapnik-dev \
    mapnik-utils python-mapnik git

